news_sites:
  dfhome:
    url: https://www.df.cl
    url_regex: ^https?://.+/.+$
    url_base: https://www.df.cl
    queries:
      homepage_article_links: 'h2.titular a'
      article_body: '.bajada'
      article_title: '.titular'

  dfempresas:
    url: https://www.df.cl/empresas
    url_regex: ^https?://.+/.+/.+$
    url_base: https://www.df.cl
    queries:
      homepage_article_links: '.noticia-horizontal a'
      article_body: '.bajada'
      article_title: '.titular'

  dfeconomia:
    url: https://www.df.cl/economia_y_politica
    url_regex: ^https?://.+/.+/.+$
    url_base: https://www.df.cl
    queries:
      homepage_article_links: '.noticia-horizontal a'
      article_body: '.bajada'
      article_title: '.titular'

  dfmercados:
    url: https://www.df.cl/mercados
    url_regex: ^https?://.+/.+/.+$
    url_base: https://www.df.cl
    queries:
      homepage_article_links: '.noticia-horizontal a'
      article_body: '.bajada'
      article_title: '.titular'